---
# tasks file for roles/todos
#
- name: playbook de prueba
  ping:

- name: "echo Obligatorio Taller 2022"
  shell: /usr/bin/echo "Obligatorio Taller 2022"
  register: Obligatorio

- name: "Salida con echo"
  debug: msg="{{ hello.stdout }}"[ansible@ansible-controller Obligatorio_2022]$ 
